In [3]:
import pandas as pd
fruits = pd.DataFrame({"Apples": [30], "Bananas": [21]})
fruits

   Apples  Bananas
0      30       21

In [ ]:
fruit_sales = pd.DataFrame({"Apples" : [35,41], "Bananas": [21,34]},index = ["2017 Sales", "2018 Sales"])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [10]:
import pandas as pd
ingredients = pd.Series(["4 cups","1 cup","2 large","1 can"], index = ["Flour", "Milk", "Eggs", "Spam"], name = "Dinner")
ingredients

#ingredients.loc["Flour"]

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [8]:
import pandas as pd
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

animals.to_csv('cows_and_goats.csv')

In [13]:
import pandas as pd
products = pd.read_csv("products.csv")
products.loc[[1,2,3,4]]
products.iloc[:4]

,Product ID,Product Name,Category,Price,Stock
0,P001,Wireless Bluetooth Headphones,Electronics,79.99,150
1,P002,Stainless Steel Water Bottle,Kitchen & Home,24.99,320
2,P003,Yoga Mat Pro,Sports & Fitness,45.00,200
3,P004,LED Desk Lamp,Office Supplies,34.50,180

In [12]:
import pandas as pd
products = pd.read_csv("products.csv")
# print(products)
products_count = products.Category.value_counts()
products_count

Category
Electronics          3
Kitchen & Home       3
Sports & Fitness     2
Office Supplies      2
Food & Beverages     1
Footwear             1
Home & Bath          1
Home Decor           1
Health & Wellness    1
Name: count, dtype: int64

In [20]:
import pandas as pd
products = pd.read_csv("products.csv")
price_to_stock_serie = products.Price / products.Stock
max_product_idx = price_to_stock_serie.idxmax()

max_product_name = products.loc[max_product_idx, "Name"]
max_product_name

" Running Shoes - Men's          "

In [18]:
import pandas as pd

df = pd.DataFrame({
    "Math" : [20, 30, 40, 50],
    "Science" : [1,2,3,4]
})

df["New_marks"] = df.apply(lambda data: data["Math"] + data["Science"], axis=1)
new = sum(df["Math"])
total = df.apply(max, axis=1)
df

   Math  Science  New_marks
0    20        1         21
1    30        2         32
2    40        3         43
3    50        4         54